# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e539ad3016ac88dbbe0f5be80f20ff388f71f131eabbff58271ba1a1d69e85054a75d7d956cfa0a93e1fb6ade8b92eabc22db865266275fad4b5ca02efc3c1e

test:
  secret_key_base: 5ea137919357f12c94508076772edcefc4898aa05b7973c8f682da8e3b3085a5af745061f2bb7d919dfafe1f0822c79f55cbe31b19fb00dc21f06f9d48cc6f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
